# Site settings
title: Yohan Lee
email: yohan9612@yonsei.ac.kr
description:  "인문학적 감성을 잃지 않는 동시에 개인화된 AI 서비스를 개발하고 싶은 자연어처리 개발자 지망생 이요한입니다."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://l-yohai.github.io/" # the base hostname & protocol for your site e.g. http://yvesespinosa.com
download_button_url: ""

# Social settings
500px_url:
facebook_url: "https://www.facebook.com/yohan.lee.75248795/"
github_url: "https://github.com/l-yohai"
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: 
pinterest_url:
twitter_url:  

# Build settings
markdown: kramdown
